export type { PoseDescriptor, BodyPartFocusSpec } from "./constants/pose";
export { POSE_MAP, POSE_MAP_MALE, BODY_PART_FOCUS_MAP, BODY_PART_FOCUS_MAP_MALE } from "./constants/pose";

export type { MoodDescriptor } from "./constants/mood";
export { MOOD_MAP, MOBILE_FRONT_MOOD_OVERRIDES } from "./constants/mood";

export {
  LIGHTING_DESCRIPTIONS,
  STYLE_MODE_MAP,
  STYLE_MODE_MAP_MALE,
  SCENE_DESCRIPTION_MAP,
  MOBILE_FRONT_SCENE_DESCRIPTION_MAP
} from "./constants/styleModes";

export {
  HAIR_STYLE_MAP,
  MOBILE_FRONT_HAIR_OVERRIDES,
  HAIR_COLOR_MAP,
  TOP_STYLE_MAP,
  BOTTOM_STYLE_MAP,
  HOSIERY_CONCEALING_BOTTOMS,
  type HosieryConcealingBottom,
  isHosieryConcealingBottom,
  HOSIERY_PEEK_REFERENCES,
  HOSIERY_TYPE_MAP,
  HOSIERY_COLOR_MAP,
  HOSIERY_MATERIAL_MAP,
  FOOTWEAR_STYLE_MAP,
  MOBILE_FRONT_FOOTWEAR_OVERRIDES,
  HAIR_CLIP_MAP,
  EARRING_MAP,
  NECK_BODY_ACCESSORIES_MAP,
  GLASSES_STYLE_MAP,
  MAKEUP_STYLE_INTENSITY_MAP,
  TOP_STYLE_INTEGRATED_BOTTOM
} from "./constants/lookups";