import { HOSIERY_DENIERS } from "./constants";

export const OPTIONS = {
    style_mode: [
        { label: "精致写真", value: "studio_elegant" },
        { label: "对镜自拍", value: "mirror_selfie" },
        { label: "手机前置自拍", value: "mobile_front" },
        { label: "第一人称互动", value: "pov_interaction" },
        { label: "身体局部特写", value: "body_part_closeup" },
        { label: "粗糙街拍", value: "rough_street_snap" }
    ],
    aspect_ratio: [
        { label: "16:9", value: "16:9" },
        { label: "9:16", value: "9:16" },
        { label: "4:3", value: "4:3" },
        { label: "3:4", value: "3:4" },
        { label: "1:1", value: "1:1" }
    ],
    pose: [
        { label: "交叉腿站立", value: "studio_runway_cross" },
        { label: "高脚凳坐姿", value: "studio_stool_legup" },
        { label: "地面后撑", value: "studio_floor_reach" },
        { label: "全身镜前站立自拍", value: "dorm_mirror_forward" },
        { label: "坐姿", value: "dorm_bed_relax" },
        { label: "跪姿", value: "dorm_floor_kneel" },
        { label: "侧躺自拍", value: "mobile_side_lie" },
        { label: "趴床自拍", value: "mobile_bed_prone" },
        { label: "日常自拍", value: "mobile_sitting" },
        { label: "单手托腮", value: "mobile_hand_on_cheek" },
        { label: "侧脸自拍", value: "mobile_side_profile" },
        { label: "比耶手势", value: "peace_sign" },
        { label: "牵手引导", value: "pov_hand_hold" },
        { label: "俯身靠近", value: "pov_overhead_hover" },
        { label: "坐在身旁", value: "pov_sit_beside" },
        { label: "伸手触碰", value: "pov_reach_to_camera" },
        { label: "下跪回眸", value: "pov_bed_twist" },
        { label: "下跪仰视", value: "pov_kneel_lookup" },
        { label: "腿部特写", value: "closeup_legs" },
        { label: "脚部特写", value: "closeup_feet" },
        { label: "臀部特写", value: "closeup_glutes" },
        { label: "腰部特写", value: "closeup_waist" },
        { label: "腹部特写", value: "closeup_abdomen" },
        { label: "背部特写", value: "closeup_back" },
        { label: "颈部特写", value: "closeup_neck" },
        { label: "胸部特写", value: "closeup_chest" },
        { label: "手臂特写", value: "closeup_arms" },
        { label: "手部特写", value: "closeup_hands" },
        { label: "回眸一瞥", value: "walking_lookback" },
        { label: "看手机", value: "checking_phone" },
        { label: "整理头发", value: "fixing_hair" },
        { label: "路边倚靠", value: "waiting_lean" },
        { label: "手持饮料", value: "holding_drink" },
        { label: "纯欲猫式", value: "kitten_lookback" },
        { label: "M字腿", value: "m_squat" },
        { label: "宽衣解带", value: "tie_adjust" },
        { label: "壁咚倚靠", value: "wall_lean" },
        { label: "咬衣角", value: "shirt_pull" }
    ],
    scene_location: [
        { label: "宿舍", value: "dorm_room" },
        { label: "浴室", value: "bathroom" },
        { label: "更衣室", value: "changing_room" },
        { label: "电梯反光门", value: "elevator_reflection" },
        { label: "健身房", value: "gym" },
        { label: "酒店", value: "hotel_suite" },
        { label: "摄影棚", value: "photo_studio" },
        { label: "城市街道", value: "city_street" },
        { label: "咖啡厅", value: "cafe" },
        { label: "公寓", value: "luxury_apartment" },
        { label: "卧室", value: "bedroom" },
        { label: "沙发", value: "sofa_lounge" },
        { label: "走廊", value: "hallway" },
        { label: "电梯内", value: "elevator_cabin" },
        { label: "街角", value: "street_corner" },
        { label: "餐馆", value: "restaurant_booth" },
        { label: "海边日落", value: "beach_sunset" },
        { label: "斑马线", value: "crosswalk" },
        { label: "便利店", value: "convenience_store" },
        { label: "地铁站台", value: "subway_platform" },
        { label: "夜市", value: "night_market" },
        { label: "汽车后座", value: "car_backseat" }
    ],
    mood: [
        { label: "吐舌", value: "playful_tongue" },
        { label: "微笑", value: "confident_smile" },
        { label: "凝视", value: "sultry_gaze" },
        { label: "阿黑颜", value: "ahegao" },
        { label: "撅嘴撒娇", value: "pitiful_gaze" },
        { label: "含泪伤心", value: "tearful_cry" }
    ],
    hair_style: [
        { label: "自然波浪", value: "natural_dark_waves" },
        { label: "自然直长发", value: "straight_long_hair" },
        { label: "松散柔卷发", value: "loose_soft_curls" },
        { label: "齐下巴波波头", value: "chin_length_bob" },
        { label: "简单马尾辫", value: "casual_ponytail" },
        { label: "双马尾", value: "twin_ponytails" },
        { label: "短纹理寸头", value: "short_textured_crop" },
        { label: "渐变undercut", value: "undercut_fade" },
        { label: "凌乱睡醒头", value: "messy_bedhead" },
        { label: "后梳油头", value: "slicked_back" },
        { label: "经典侧分", value: "side_part_classic" },
        { label: "中性精灵头", value: "androgynous_pixie" }
    ],
    hair_color: [
        { label: "随机", value: "random" },
        { label: "黑色", value: "black" },
        { label: "棕色", value: "brown" },
        { label: "白色", value: "white" },
        { label: "灰色", value: "gray" },
        { label: "粉色", value: "pink" },
        { label: "绿色", value: "green" },
        { label: "蓝色", value: "blue" },
        { label: "红色", value: "red" },
        { label: "紫色", value: "purple" },
        { label: "金色", value: "blonde" },
        { label: "橙色", value: "orange" }
    ],
    top_style: [
        { label: "无上衣", value: "none" },
        { label: "简约短袖上衣", value: "casual_tee" },
        { label: "柔软衬衫/衬衣", value: "soft_blouse" },
        { label: "轻薄针织衫", value: "knit_sweater" },
        { label: "温暖毛衣", value: "cozy_sweater" },
        { label: "紧身羊毛衫", value: "fitted_wool_top" },
        { label: "吊带/背心", value: "sleek_camisole" },
        { label: "网纱上衣", value: "mesh_top" },
        { label: "连体泳衣", value: "one_piece_swimsuit" },
        { label: "JK 制服套装", value: "jk_uniform" },
        { label: "连衣裙", value: "one_piece_dress" },
        { label: "高叉旗袍", value: "high_slit_cheongsam" },
        { label: "男式西服套装", value: "mens_suit" },
        { label: "女式西服套装", value: "womens_suit" },
        { label: "真丝睡衣", value: "silk_nightgown" },
        { label: "西装（无内搭）", value: "blazer_no_underlay" },
        { label: "纽扣衬衫", value: "button_down_shirt" },
        { label: "连帽衫", value: "hoodie" },
        { label: "运动背心", value: "tank_top" },
        { label: "宽松毛衣", value: "oversized_sweater" },
        { label: "V领T恤", value: "v_neck_tee" },
        { label: "亨利领T恤", value: "henley_shirt" },
        { label: "浴巾", value: "bath_towel" }
    ],
    bottom_style: [
        { label: "无下装", value: "none" },
        { label: "基础迷你裙", value: "mini_skirt" },
        { label: "及膝/中长裙", value: "midi_skirt" },
        { label: "包臀长裙", value: "body_conscious_maxi_skirt" },
        { label: "修身长裤", value: "tailored_trousers" },
        { label: "瑜伽裤", value: "yoga_leggings" },
        { label: "经典牛仔裤", value: "denim_jeans" },
        { label: "休闲短裤", value: "casual_shorts" },
        { label: "泳装短裤", value: "swim_trunks" },
        { label: "工装裤", value: "cargo_pants" },
        { label: "卡其裤", value: "chino_pants" },
        { label: "运动短裤", value: "athletic_shorts" },
        { label: "阔腿裤", value: "wide_leg_pants" },
        { label: "西裤", value: "pleated_trousers" },
        { label: "灰色卫裤", value: "sweatpants" },
        { label: "浴巾", value: "bath_towel" }
    ],
    hosiery_type: [
        { label: "连裤袜", value: "pantyhose" },
        { label: "吊带袜", value: "garter" },
        { label: "大腿袜", value: "thigh_high" },
        { label: "及膝袜", value: "knee_high" },
        { label: "小腿袜", value: "calf_sock" },
        { label: "短袜", value: "ankle_sock" },
        { label: "渔网袜", value: "fishnet" }
    ],
    hosiery_color: [
        { label: "随机色", value: "random" },
        { label: "黑色", value: "black" },
        { label: "灰色", value: "gray" },
        { label: "白色", value: "white" },
        { label: "棕色", value: "brown" }
    ],
    hosiery_material: [
        { label: "天鹅绒", value: "velvet" },
        { label: "包芯丝", value: "core_spun" },
        { label: "马油光泽", value: "glossy" },
        { label: "羊毛混纺", value: "woolen" },
        { label: "大格渔网", value: "fishnet_large" },
        { label: "小格渔网", value: "fishnet_small" },
        { label: "棉质", value: "cotton" },
        { label: "粗针织", value: "knit" }
    ],
    hosiery_denier: HOSIERY_DENIERS.map((d) => ({
        label: `${d}D`,
        value: String(d)
    })),
    footwear_style: [
        { label: "光脚", value: "barefoot" },
        { label: "漆皮细高跟鞋", value: "patent_heels" },
        { label: "厚底短靴", value: "platform_boots" },
        { label: "利落尖头穆勒鞋", value: "sleek_mules" },
        { label: "日常运动鞋", value: "casual_sneakers" },
        { label: "长靴", value: "tall_boots" },
        { label: "勃肯凉拖", value: "birken_sandals" },
        { label: "洞洞鞋", value: "foam_clogs" },
        { label: "居家拖鞋", value: "home_slippers" },
        { label: "制服乐福鞋", value: "uniform_loafers" },
        { label: "浅口平底鞋", value: "low_cut_flats" },
        { label: "高帮运动鞋", value: "high_top_sneakers" },
        { label: "皮靴", value: "leather_boots" },
        { label: "帆布鞋", value: "canvas_sneakers" },
        { label: "一脚蹬运动鞋", value: "slip_on_sneakers" },
        { label: "正装皮鞋", value: "dress_shoes" }
    ],
    hair_clip: [
        { label: "无发饰", value: "none" },
        { label: "哑光抓夹", value: "matte_claw_clip" },
        { label: "简约发卡", value: "simple_barrette" },
        { label: "柔软头箍", value: "soft_headband" }
    ],
    earrings: [
        { label: "无耳饰", value: "none" },
        { label: "极简耳钉", value: "minimal_studs" },
        { label: "细长垂坠耳饰", value: "delicate_drops" },
        { label: "干净圆环耳饰", value: "clean_hoops" }
    ],
    neck_body_accessories: [
        { label: "无配饰", value: "none" },
        { label: "项圈", value: "choker" },
        { label: "身体链", value: "body_chain" }
    ],
    glasses_style: [
        { label: "无眼镜", value: "none" },
        { label: "无框眼镜", value: "metal_rimless" },
        { label: "半框眼镜", value: "semi_rimless" },
        { label: "金丝框眼镜", value: "gold_wire_frame" },
        { label: "全框眼镜", value: "full_frame" },
        { label: "飞行员墨镜", value: "aviator_sunglasses" },
        { label: "猫眼墨镜", value: "cat_eye_sunglasses" }
    ],
    makeup_style: [
        { label: "自然", value: "natural" },
        { label: "甜美", value: "sweet" },
        { label: "成熟", value: "mature" },
        { label: "性感", value: "sultry" }
    ],
    makeup_intensity: [
        { label: "淡", value: "light" },
        { label: "中", value: "medium" },
        { label: "浓", value: "intense" }
    ],
    gender: [
        { label: "女性", value: "female" },
        { label: "男性", value: "male" },
        { label: "无性别", value: "agender" }
    ],
    ethnicity: [
        { label: "随机", value: "random" },
        { label: "东亚", value: "east_asian" },
        { label: "南亚", value: "south_asian" },
        { label: "东南亚", value: "southeast_asian" },
        { label: "欧美", value: "white_caucasian" },
        { label: "非洲", value: "black_african" },
        { label: "拉丁", value: "hispanic_latino" },
        { label: "中东", value: "middle_eastern" },
        { label: "混血", value: "mixed" }
    ],
    female_body_type: [
        { label: "梨形", value: "pear" },
        { label: "娇小", value: "petite" },
        { label: "丰满", value: "full" },
        { label: "肥美", value: "voluptuous" },
        { label: "超模", value: "model" },
        { label: "沙漏", value: "hourglass" }
    ],
    male_body_type: [
        { label: "美少年", value: "lean" },
        { label: "体育生", value: "toned" },
        { label: "男妈妈", value: "muscle_bulky" },
        { label: "脂包肌", value: "beefy" },
        { label: "胖墩", value: "chubby" }
    ]
} as const;